# This is the configuration used to check the rubocop source code.

# uncomment the following line if you get blocked by rubocop
#inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.6
  NewCops: enable

Rails:
  Enable: true


Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier: 
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Lambda:
  Enabled: true
  EnforcedStyle: literal

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

Layout/HeredocIndentation:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'spec/**/*'
  CountComments: false  # count full line comments?
  Max: 80


Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
  CountComments: false  # count full line comments?
  Max: 500

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 20

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 500


Layout/LineLength:
  Max: 175
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  # The IgnoreCopDirectives option causes the LineLength rule to ignore cop
  # directives like '# rubocop: enable ...' when calculating a line's length.
  IgnoreCopDirectives: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 80


Metrics/PerceivedComplexity:
  Max: 10

Documentation:
  Enabled: false


