version: '3'

services:

  # redis:
  #   image: redis
  #   restart: always

  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    volumes:
      - ./docker/data/postgres/etc:/etc/postgresql
      - ./docker/data/postgres/log:/var/log/postgresql
      - ./docker/data/postgres/lib/data:/var/lib/postgresql/data
    restart: always
      
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  rails:
    stdin_open: true
    tty: true
    build: .
    env_file:
      - .env
    volumes:
      - .:/rails
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://rails:rails@postgres:5432/rails
      MAILCATCHER_SMTP_ADDRESS: mailcatcher
      MAILCATCHER_SMTP_PORT: 1025
