version: '3'

services:

  # redis:
  #   image: redis
  #   restart: always

  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: rails
    volumes:
      - ./docker/data/postgres/etc:/etc/postgresql
      - ./docker/data/postgres/log:/var/log/postgresql
      - ./docker/data/postgres/lib/data:/var/lib/postgresql/data
    restart: always

  rails:
    build: .
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://rails:rails@postgres:5432/rails
