name: Lint

on: pull_request

jobs:
  rubocop:
    # On fetching origin/<target branch> https://github.com/actions/checkout/issues/438#issuecomment-1099284053
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - run: git diff-tree -r --name-only HEAD~1 HEAD | grep -E '\.rb$' | xargs -r bundle exec rubocop
