name: Default

on:
  push:
    branches:
      - master
      - develop
      - build/*
    tags:
      - v*

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: rails
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install postgres client
        run: sudo apt-get -yqq install libpq-dev

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run tests
        env:
          DATABASE_URL: postgres://localhost@127.0.0.1:5432/rails
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec

  build:

    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile.release
          tag_with_ref: true
          repository: milleetunmots/app
          cache_froms: milleetunmots/app:develop
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          always_pull: true
