name: Default

on:
  push:
    branches:
      - master
      - develop
      - build/*
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build & Push
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile.release
        repository: milleetunmots/app
        tag_with_ref: true
