name: Default

on:
  push:
    branches:
      - master
      - develop
      - build/*
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v1
    - name: Build & Push
    - with:
      dockerfile: Dockerfile.release
      repository: milleetunmots/app
      tag_with_ref: true
