name: Default

on:
  push:
    branches:
      - master
      - develop
      - build/*
    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile.release
          tag_with_ref: true
          repository: milleetunmots/app
          cache_froms: milleetunmots/app:develop
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
